/* Correctness tests for sycl/ds4_sycl_attention.hpp: raw KV store, the FP8
 * KV store composition, and single-token decode attention.
 *
 * Oracle selection: ds4.c has seven candidate CPU attention implementations
 * (layer_attention_one, _rows_one, _mixed_one, _mixed_one_decode_scratch,
 * _prefix_batch[_worker], _raw_swa_one, _raw_swa_batch). The single-token
 * decode entry ds4_gpu_attention_decode_heads_tensor is matched to
 * layer_attention_mixed_one (ds4.c:12693), confirmed rather than assumed by
 * tracing its real call sites in ds4.c: every one of the three call sites
 * of ds4_gpu_attention_decode_heads_tensor (ds4.c:23161, 23216, 23293)
 * passes use_mask=0, comp_mask=NULL, while n_comp may be nonzero (a
 * compressed-KV layer at a ratio other than 4). layer_attention_mixed_one
 * is reached with its comp_allowed argument NULL in exactly that
 * circumstance: layer_attention_raw_swa_one (ds4.c:13062) only populates
 * comp_allowed via indexer_allowed_decode_one when compress_ratio == 4
 * (ds4.c:13123), leaving it NULL for every other nonzero ratio, and
 * layer_attention_mixed_one treats a NULL comp_allowed as "every compressed
 * row is visible" (ds4.c:12719-12723). So the real production shape this
 * entry serves is exactly layer_attention_mixed_one with comp_allowed =
 * NULL: no other one of the seven candidates matches that call shape (the
 * _rows_one variant takes one undifferentiated KV block with no raw/comp
 * split at all, and the _prefix_batch/_raw_swa_batch variants are for
 * n_tokens > 1). The oracle below transcribes layer_attention_mixed_one's
 * math, adapted for the ring-buffer raw_cap/raw_start addressing the GPU
 * kernel and the ABI actually use (layer_attention_mixed_one's own
 * cache->raw_kv argument is a pre-extracted linear view, so it does not
 * need the ring arithmetic itself; the underlying rows fetched are the
 * same regardless of which side does the extraction).
 *
 * Per spec 6f, softmax is a normaliser: a uniform scale error upstream
 * divides straight out. Test data is generated by a small deterministic
 * hash (test_prand) combining head, row and dim indices multiplicatively
 * and with XOR-mixing, not by any affine expression in the indices, so a
 * scale-only or head-swapped perturbation is not invisible to the
 * assertions. */

#include "ds4_gpu.h"
#include "ds4_gpu_mgpu.h"

#include "test_sycl_harness.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Deterministic hash-based pseudo-random float in [-1, 1]. Combines its
 * inputs with multiplication and xor-mixing (murmur-style finaliser) so the
 * result is not affine in any index, per spec 6f/6n: an affine generator
 * makes every element proportional to every other, which is exactly the
 * degeneracy that hides a scale-only error or a reduction reordering bug. */
static float test_prand(uint32_t a, uint32_t b, uint32_t c) {
    uint32_t seed = a * 2654435761u + b * 2246822519u + c * 3266489917u;
    seed ^= seed >> 16;
    seed *= 0x7feb352du;
    seed ^= seed >> 15;
    seed *= 0x846ca68bu;
    seed ^= seed >> 16;
    return ((float)(seed & 0xFFFFFu) / (float)0xFFFFF) * 2.0f - 1.0f;
}

/* Oracle for ds4_gpu_attention_decode_heads_tensor, transcribing
 * layer_attention_mixed_one (ds4.c:12693-12753) with comp_allowed == NULL
 * (see file comment above), and reading raw rows through the same
 * raw_cap/raw_start ring addressing attention_decode_mixed_one_fast_oldhip_
 * kernel uses (attention.cuh:547-548), since this test's raw_kv buffer is a
 * physical ring rather than layer_attention_mixed_one's pre-extracted
 * linear view. */
static void oracle_attention_decode_heads(
        float *out_heads, const float *sinks, const float *q,
        const float *raw_kv, uint32_t n_raw, uint32_t raw_cap, uint32_t raw_start,
        const float *comp_kv, uint32_t n_comp,
        const float *comp_mask, int use_mask,
        uint32_t n_head, uint32_t head_dim) {
    const float scale = 1.0f / sqrtf((float)head_dim);
    float *scores = (float *)malloc((size_t)(n_raw + n_comp + 1u) * sizeof(float));
    for (uint32_t h = 0; h < n_head; h++) {
        const float *qh = q + (uint64_t)h * head_dim;
        float max_score = sinks[h];
        for (uint32_t r = 0; r < n_raw; r++) {
            const uint32_t row = raw_cap ? (raw_start + r) % raw_cap : r;
            const float *kv = raw_kv + (uint64_t)row * head_dim;
            float dot = 0.0f;
            for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
            scores[r] = dot * scale;
            if (scores[r] > max_score) max_score = scores[r];
        }
        for (uint32_t c = 0; c < n_comp; c++) {
            float s;
            if (use_mask && comp_mask[c] <= -5.0e29f) {
                s = -3.4e38f;
            } else {
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                s = dot * scale;
                if (use_mask) s += comp_mask[c];
            }
            scores[n_raw + c] = s;
            if (s > max_score) max_score = s;
        }

        float *oh = out_heads + (uint64_t)h * head_dim;
        memset(oh, 0, (size_t)head_dim * sizeof(float));
        float denom = expf(sinks[h] - max_score);
        for (uint32_t r = 0; r < n_raw; r++) {
            const float w = expf(scores[r] - max_score);
            denom += w;
            const uint32_t row = raw_cap ? (raw_start + r) % raw_cap : r;
            const float *kv = raw_kv + (uint64_t)row * head_dim;
            for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
        }
        for (uint32_t c = 0; c < n_comp; c++) {
            const float w = expf(scores[n_raw + c] - max_score);
            denom += w;
            const float *kv = comp_kv + (uint64_t)c * head_dim;
            for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
        }
        for (uint32_t d = 0; d < head_dim; d++) oh[d] /= denom;
    }
    free(scores);
}

/* F16 round-trip matching sycl_f32_to_f16_bits_hip_round / f16_bits_to_f32,
 * transcribed identically to the oracle already established in
 * tests/test_sycl_fp8_kv.c (dsv4-adjacent), since ds4_gpu_store_raw_kv_tensor
 * delegates to the already-tested store_raw_kv_batch_kernel path. */
static uint16_t oracle_f32_to_f16_hip_round(float f) {
    uint32_t u;
    memcpy(&u, &f, sizeof(u));
    uint32_t sign = (u >> 16) & 0x8000u;
    int32_t exp = (int32_t)((u >> 23) & 0xffu) - 127 + 15;
    uint32_t mant = u & 0x7fffffu;
    if (exp <= 0) {
        if (exp < -10) return (uint16_t)sign;
        mant |= 0x800000u;
        uint32_t shift = (uint32_t)(14 - exp);
        uint32_t half_mant = mant >> shift;
        if ((mant >> (shift - 1)) & 1u) half_mant++;
        return (uint16_t)(sign | half_mant);
    }
    if (exp >= 31) return (uint16_t)(sign | 0x7c00u);
    uint32_t half = sign | ((uint32_t)exp << 10) | (mant >> 13);
    if (mant & 0x1000u) half++;
    return (uint16_t)half;
}

static float oracle_f16_round_trip(float f) {
    return oracle_half_to_float(oracle_f32_to_f16_hip_round(f));
}

#define HEAD_DIM_KV 16u

static int test_store_raw_kv(void) {
    const uint32_t raw_cap = 8u;
    const uint32_t row = 5u;
    float kv[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) kv[d] = test_prand(1u, d, 7u) * 3.0f;

    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * HEAD_DIM_KV * sizeof(float));
    ds4_gpu_tensor *tkv = ds4_gpu_tensor_alloc((uint64_t)HEAD_DIM_KV * sizeof(float));
    CHECK(traw && tkv, "store_raw_kv: alloc failed");
    float zeros[8u * HEAD_DIM_KV];
    memset(zeros, 0, sizeof(zeros));
    CHECK(ds4_gpu_tensor_write(traw, 0, zeros, sizeof(zeros)) != 0, "store_raw_kv: zero init failed");
    CHECK(ds4_gpu_tensor_write(tkv, 0, kv, sizeof(kv)) != 0, "store_raw_kv: kv write failed");

    CHECK(ds4_gpu_store_raw_kv_tensor(traw, tkv, raw_cap, row, HEAD_DIM_KV) != 0,
          "store_raw_kv: launch failed");

    float got[8u * HEAD_DIM_KV];
    CHECK(ds4_gpu_tensor_read(traw, 0, got, sizeof(got)) != 0, "store_raw_kv: read failed");
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        CHECK_CLOSE(got[row * HEAD_DIM_KV + d], oracle_f16_round_trip(kv[d]), 1e-6,
                    "store_raw_kv: stored row mismatch");
    }
    for (uint32_t r = 0; r < raw_cap; r++) {
        if (r == row) continue;
        for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
            CHECK(got[r * HEAD_DIM_KV + d] == 0.0f, "store_raw_kv: unrelated row disturbed");
        }
    }

    CHECK(ds4_gpu_store_raw_kv_tensor(NULL, tkv, raw_cap, row, HEAD_DIM_KV) == 0,
          "store_raw_kv: null raw_cache must be rejected");
    CHECK(ds4_gpu_store_raw_kv_tensor(traw, tkv, 0u, row, HEAD_DIM_KV) == 0,
          "store_raw_kv: raw_cap == 0 must be rejected");

    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tkv);
    fprintf(stderr, "  test_store_raw_kv OK\n");
    return 0;
}

/* Oracle for the FP8 quantiser's non-RoPE scaling, transcribed from
 * dsv4_fp8_kv_quantize_row_inplace_cpu's per-block-max/scale/dequant shape
 * (ds4.c:3241-3261) and already exercised directly in
 * tests/test_sycl_fp8_kv.c; here it is only composed with the store, so the
 * test checks the composition rather than re-deriving the quantiser oracle
 * in full: the non-RoPE prefix is quantised to a single shared per-row
 * scale (max-abs over the whole n_nope prefix, since n_nope == HEAD_DIM_KV
 * fits in the quantiser's one 64-wide group), each value snapped to the
 * nearest representable E4M3 magnitude, then F16-round-tripped by the
 * store. */
static float oracle_e4m3fn_value(int code) {
    static const float exp_scale[16] = {
        0.0f, 0.015625f, 0.03125f, 0.0625f, 0.125f, 0.25f, 0.5f, 1.0f,
        2.0f, 4.0f, 8.0f, 16.0f, 32.0f, 64.0f, 128.0f, 256.0f,
    };
    const int exp = (code >> 3) & 0x0f;
    const int mant = code & 0x07;
    return exp == 0 ? (float)mant * 0.001953125f : (1.0f + (float)mant * 0.125f) * exp_scale[exp];
}

static float oracle_e4m3fn_dequant(float x) {
    const float sign = x < 0.0f ? -1.0f : 1.0f;
    const float ax = fminf(fabsf(x), 448.0f);
    int lo = 0, hi = 126;
    while (lo < hi) {
        const int mid = (lo + hi + 1) >> 1;
        if (oracle_e4m3fn_value(mid) <= ax) lo = mid; else hi = mid - 1;
    }
    int best = lo;
    if (best < 126) {
        const float best_diff = fabsf(ax - oracle_e4m3fn_value(best));
        const float next_diff = fabsf(ax - oracle_e4m3fn_value(best + 1));
        if (next_diff < best_diff || (next_diff == best_diff && ((best + 1) & 1) == 0 && (best & 1) != 0)) best++;
    }
    return sign * oracle_e4m3fn_value(best);
}

static int test_kv_fp8_store_raw(void) {
    const uint32_t raw_cap = 4u;
    const uint32_t row = 2u;
    const uint32_t n_rot = 0u; /* whole row is quantised: n_nope == head_dim */
    float kv[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) kv[d] = test_prand(2u, d, 11u) * 5.0f;

    float row_max = 1.0e-4f;
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) if (fabsf(kv[d]) > row_max) row_max = fabsf(kv[d]);
    const float scale = exp2f(ceilf(log2f(row_max / 448.0f)));
    float want[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        const float clamped = fminf(448.0f, fmaxf(-448.0f, kv[d] / scale));
        want[d] = oracle_f16_round_trip(oracle_e4m3fn_dequant(clamped) * scale);
    }

    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * HEAD_DIM_KV * sizeof(float));
    ds4_gpu_tensor *tkv = ds4_gpu_tensor_alloc((uint64_t)HEAD_DIM_KV * sizeof(float));
    CHECK(traw && tkv, "kv_fp8_store_raw: alloc failed");
    float zeros[4u * HEAD_DIM_KV];
    memset(zeros, 0, sizeof(zeros));
    CHECK(ds4_gpu_tensor_write(traw, 0, zeros, sizeof(zeros)) != 0, "kv_fp8_store_raw: zero init failed");
    CHECK(ds4_gpu_tensor_write(tkv, 0, kv, sizeof(kv)) != 0, "kv_fp8_store_raw: kv write failed");

    CHECK(ds4_gpu_kv_fp8_store_raw_tensor(tkv, traw, raw_cap, row, HEAD_DIM_KV, n_rot) != 0,
          "kv_fp8_store_raw: launch failed");

    float got[4u * HEAD_DIM_KV];
    CHECK(ds4_gpu_tensor_read(traw, 0, got, sizeof(got)) != 0, "kv_fp8_store_raw: read failed");
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        CHECK_CLOSE(got[row * HEAD_DIM_KV + d], want[d], 1e-3, "kv_fp8_store_raw: stored row mismatch");
    }

    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tkv);
    fprintf(stderr, "  test_kv_fp8_store_raw OK\n");
    return 0;
}

#define DH_N_HEAD 4u
#define DH_HEAD_DIM 16u
#define DH_N_RAW 300u
#define DH_RAW_CAP 350u
#define DH_RAW_START 300u
#define DH_N_COMP 200u

typedef struct {
    float sinks[DH_N_HEAD];
    float q[DH_N_HEAD * DH_HEAD_DIM];
    float raw_kv[DH_RAW_CAP * DH_HEAD_DIM];
    float comp_kv[DH_N_COMP * DH_HEAD_DIM];
    float comp_mask[DH_N_COMP];
} dh_fixture;

static void dh_fixture_build(dh_fixture *fx) {
    for (uint32_t h = 0; h < DH_N_HEAD; h++) fx->sinks[h] = test_prand(h, 999u, 3u) * 2.0f;
    for (uint32_t h = 0; h < DH_N_HEAD; h++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->q[h * DH_HEAD_DIM + d] = test_prand(h, d, 101u);
        }
    }
    for (uint32_t r = 0; r < DH_RAW_CAP; r++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->raw_kv[r * DH_HEAD_DIM + d] = test_prand(r, d, 202u);
        }
    }
    for (uint32_t c = 0; c < DH_N_COMP; c++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->comp_kv[c * DH_HEAD_DIM + d] = test_prand(c, d, 303u);
        }
        fx->comp_mask[c] = 0.0f;
    }
}

/* Model buffer holding only attn_sinks, at a nonzero offset so a test that
 * accidentally reads from offset 0 (or fails to apply sinks_offset at all)
 * is caught rather than accidentally passing. */
typedef struct {
    unsigned char *bytes;
    uint64_t       size;
    uint64_t       sinks_offset;
} dh_model;

static dh_model dh_model_build(const float *sinks, uint32_t n_head) {
    dh_model m;
    m.sinks_offset = 64u;
    m.size = m.sinks_offset + (uint64_t)n_head * sizeof(float);
    m.bytes = (unsigned char *)calloc(1, (size_t)m.size);
    memcpy(m.bytes + m.sinks_offset, sinks, (size_t)n_head * sizeof(float));
    return m;
}

static int dh_run_and_check(const dh_fixture *fx, uint32_t n_raw, uint32_t raw_cap,
                            uint32_t raw_start, uint32_t n_comp, const char *what) {
    dh_model model = dh_model_build(fx->sinks, DH_N_HEAD);

    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = n_comp ? ds4_gpu_tensor_alloc((uint64_t)n_comp * DH_HEAD_DIM * sizeof(float)) : NULL;
    CHECK(theads && tq && traw && (n_comp == 0 || tcomp), "decode_heads: alloc failed");

    CHECK(ds4_gpu_tensor_write(tq, 0, fx->q, sizeof(fx->q)) != 0, "decode_heads: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx->raw_kv, (uint64_t)raw_cap * DH_HEAD_DIM * sizeof(float)) != 0,
          "decode_heads: raw_kv write failed");
    if (n_comp) {
        CHECK(ds4_gpu_tensor_write(tcomp, 0, fx->comp_kv, (uint64_t)n_comp * DH_HEAD_DIM * sizeof(float)) != 0,
              "decode_heads: comp_kv write failed");
    }

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset,
              tq, traw, n_raw, raw_cap, raw_start,
              tcomp, /*comp_kv_f16=*/0u, n_comp,
              /*comp_mask=*/NULL, /*use_mask=*/0u,
              DH_N_HEAD, DH_HEAD_DIM) != 0,
          "decode_heads: launch failed");

    float got[DH_N_HEAD * DH_HEAD_DIM];
    CHECK(ds4_gpu_tensor_read(theads, 0, got, sizeof(got)) != 0, "decode_heads: read failed");

    float want[DH_N_HEAD * DH_HEAD_DIM];
    oracle_attention_decode_heads(want, fx->sinks, fx->q, fx->raw_kv, n_raw, raw_cap, raw_start,
                                  fx->comp_kv, n_comp, NULL, 0, DH_N_HEAD, DH_HEAD_DIM);

    int rc = 0;
    for (uint32_t i = 0; i < DH_N_HEAD * DH_HEAD_DIM && rc == 0; i++) {
        char msg[96];
        snprintf(msg, sizeof(msg), "%s: heads[%u] mismatch", what, i);
        if (fabs((double)got[i] - (double)want[i]) > 1e-3) {
            fprintf(stderr, "FAIL: %s (got %.9g want %.9g)\n", msg, (double)got[i], (double)want[i]);
            rc = 1;
        }
    }

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    if (tcomp) ds4_gpu_tensor_free(tcomp);
    free(model.bytes);
    return rc;
}

static int test_decode_heads_mixed_wraparound(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    CHECK(dh_run_and_check(&fx, DH_N_RAW, DH_RAW_CAP, DH_RAW_START, DH_N_COMP,
                           "decode_heads mixed+wraparound") == 0,
          "decode_heads mixed+wraparound failed");
    fprintf(stderr, "  test_decode_heads_mixed_wraparound OK\n");
    return 0;
}

static int test_decode_heads_raw_only(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    CHECK(dh_run_and_check(&fx, DH_N_RAW, DH_RAW_CAP, DH_RAW_START, 0u,
                           "decode_heads raw-only") == 0,
          "decode_heads raw-only failed");
    fprintf(stderr, "  test_decode_heads_raw_only OK\n");
    return 0;
}

/* Validation-only cases, matching the ROCm launcher's zero-work and
 * argument-rejection shape. */
static int test_decode_heads_validation(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    dh_model model = dh_model_build(fx.sinks, DH_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)DH_RAW_CAP * DH_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw, "decode_heads validation: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, fx.q, sizeof(fx.q)) != 0, "decode_heads validation: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx.raw_kv, sizeof(fx.raw_kv)) != 0,
          "decode_heads validation: raw_kv write failed");

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              /*n_raw=*/0u, DH_RAW_CAP, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: n_raw == 0 must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, /*raw_cap=*/DH_N_RAW - 1u, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: raw_cap < n_raw must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, /*sinks_offset=*/model.size + 1u, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: sinks_offset past model_size must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, NULL, /*comp_kv_f16=*/1u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: comp_kv_f16 must be rejected");

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    free(model.bytes);
    fprintf(stderr, "  test_decode_heads_validation OK\n");
    return 0;
}

/* Cross-check within the mask-additive representation, exercised even
 * though every real ds4.c call site always passes use_mask == 0 (see the
 * file comment's oracle derivation): the ABI entry still declares this
 * parameter, so its documented behaviour is verified directly rather than
 * left untested because production never reaches it today. */
static int test_decode_heads_masked(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    /* Disallow every third compressed row via the -1e30 sentinel; allow
     * the rest with a nonzero additive bias so the mask's two behaviours
     * (hard exclude vs. additive bias) are both exercised. */
    for (uint32_t c = 0; c < DH_N_COMP; c++) {
        fx.comp_mask[c] = (c % 3u == 0u) ? -1.0e30f : test_prand(c, 777u, 5u) * 0.5f;
    }

    dh_model model = dh_model_build(fx.sinks, DH_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)DH_RAW_CAP * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)DH_N_COMP * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tmask = ds4_gpu_tensor_alloc((uint64_t)DH_N_COMP * sizeof(float));
    CHECK(theads && tq && traw && tcomp && tmask, "decode_heads masked: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, fx.q, sizeof(fx.q)) != 0, "decode_heads masked: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx.raw_kv, sizeof(fx.raw_kv)) != 0,
          "decode_heads masked: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, fx.comp_kv, sizeof(fx.comp_kv)) != 0,
          "decode_heads masked: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(tmask, 0, fx.comp_mask, sizeof(fx.comp_mask)) != 0,
          "decode_heads masked: mask write failed");

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, tcomp, 0u, DH_N_COMP,
              tmask, /*use_mask=*/1u, DH_N_HEAD, DH_HEAD_DIM) != 0,
          "decode_heads masked: launch failed");

    float got[DH_N_HEAD * DH_HEAD_DIM];
    CHECK(ds4_gpu_tensor_read(theads, 0, got, sizeof(got)) != 0, "decode_heads masked: read failed");
    float want[DH_N_HEAD * DH_HEAD_DIM];
    oracle_attention_decode_heads(want, fx.sinks, fx.q, fx.raw_kv, DH_N_RAW, DH_RAW_CAP, DH_RAW_START,
                                  fx.comp_kv, DH_N_COMP, fx.comp_mask, 1, DH_N_HEAD, DH_HEAD_DIM);
    for (uint32_t i = 0; i < DH_N_HEAD * DH_HEAD_DIM; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "decode_heads masked: heads mismatch");
    }

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp);
    ds4_gpu_tensor_free(tmask);
    free(model.bytes);
    fprintf(stderr, "  test_decode_heads_masked OK\n");
    return 0;
}

int main(void) {
    CHECK(ds4_gpu_init() != 0, "ds4_gpu_init failed");
    if (test_store_raw_kv() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_kv_fp8_store_raw() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_mixed_wraparound() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_raw_only() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_masked() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_validation() != 0) { ds4_gpu_cleanup(); return 1; }
    ds4_gpu_cleanup();
    fprintf(stderr, "  test_sycl_attention OK\n");
    return 0;
}
