/* Correctness tests for sycl/ds4_sycl_attention.hpp: raw KV store, the FP8
 * KV store composition, and single-token decode attention.
 *
 * Oracle selection: ds4.c has seven candidate CPU attention implementations
 * (layer_attention_one, _rows_one, _mixed_one, _mixed_one_decode_scratch,
 * _prefix_batch[_worker], _raw_swa_one, _raw_swa_batch). The single-token
 * decode entry ds4_gpu_attention_decode_heads_tensor is matched to
 * layer_attention_mixed_one (ds4.c:12693), confirmed rather than assumed by
 * tracing its real call sites in ds4.c: every one of the three call sites
 * of ds4_gpu_attention_decode_heads_tensor (ds4.c:23161, 23216, 23293)
 * passes use_mask=0, comp_mask=NULL, while n_comp may be nonzero (a
 * compressed-KV layer at a ratio other than 4). layer_attention_mixed_one
 * is reached with its comp_allowed argument NULL in exactly that
 * circumstance: layer_attention_raw_swa_one (ds4.c:13062) only populates
 * comp_allowed via indexer_allowed_decode_one when compress_ratio == 4
 * (ds4.c:13123), leaving it NULL for every other nonzero ratio, and
 * layer_attention_mixed_one treats a NULL comp_allowed as "every compressed
 * row is visible" (ds4.c:12719-12723). So the real production shape this
 * entry serves is exactly layer_attention_mixed_one with comp_allowed =
 * NULL: no other one of the seven candidates matches that call shape (the
 * _rows_one variant takes one undifferentiated KV block with no raw/comp
 * split at all, and the _prefix_batch/_raw_swa_batch variants are for
 * n_tokens > 1). The oracle below transcribes layer_attention_mixed_one's
 * math, adapted for the ring-buffer raw_cap/raw_start addressing the GPU
 * kernel and the ABI actually use (layer_attention_mixed_one's own
 * cache->raw_kv argument is a pre-extracted linear view, so it does not
 * need the ring arithmetic itself; the underlying rows fetched are the
 * same regardless of which side does the extraction).
 *
 * Per spec 6f, softmax is a normaliser: a uniform scale error upstream
 * divides straight out. Test data is generated by a small deterministic
 * hash (test_prand) combining head, row and dim indices multiplicatively
 * and with XOR-mixing, not by any affine expression in the indices, so a
 * scale-only or head-swapped perturbation is not invisible to the
 * assertions. */

#include "ds4_gpu.h"
#include "ds4_gpu_mgpu.h"

#include "test_sycl_harness.h"

#include <math.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

/* Deterministic hash-based pseudo-random float in [-1, 1]. Combines its
 * inputs with multiplication and xor-mixing (murmur-style finaliser) so the
 * result is not affine in any index, per spec 6f/6n: an affine generator
 * makes every element proportional to every other, which is exactly the
 * degeneracy that hides a scale-only error or a reduction reordering bug. */
static float test_prand(uint32_t a, uint32_t b, uint32_t c) {
    uint32_t seed = a * 2654435761u + b * 2246822519u + c * 3266489917u;
    seed ^= seed >> 16;
    seed *= 0x7feb352du;
    seed ^= seed >> 15;
    seed *= 0x846ca68bu;
    seed ^= seed >> 16;
    return ((float)(seed & 0xFFFFFu) / (float)0xFFFFF) * 2.0f - 1.0f;
}

/* Oracle for ds4_gpu_attention_decode_heads_tensor, transcribing
 * layer_attention_mixed_one (ds4.c:12693-12753) with comp_allowed == NULL
 * (see file comment above), and reading raw rows through the same
 * raw_cap/raw_start ring addressing attention_decode_mixed_one_fast_oldhip_
 * kernel uses (attention.cuh:547-548), since this test's raw_kv buffer is a
 * physical ring rather than layer_attention_mixed_one's pre-extracted
 * linear view. */
static void oracle_attention_decode_heads(
        float *out_heads, const float *sinks, const float *q,
        const float *raw_kv, uint32_t n_raw, uint32_t raw_cap, uint32_t raw_start,
        const float *comp_kv, uint32_t n_comp,
        const float *comp_mask, int use_mask,
        uint32_t n_head, uint32_t head_dim) {
    const float scale = 1.0f / sqrtf((float)head_dim);
    float *scores = (float *)malloc((size_t)(n_raw + n_comp + 1u) * sizeof(float));
    for (uint32_t h = 0; h < n_head; h++) {
        const float *qh = q + (uint64_t)h * head_dim;
        float max_score = sinks[h];
        for (uint32_t r = 0; r < n_raw; r++) {
            const uint32_t row = raw_cap ? (raw_start + r) % raw_cap : r;
            const float *kv = raw_kv + (uint64_t)row * head_dim;
            float dot = 0.0f;
            for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
            scores[r] = dot * scale;
            if (scores[r] > max_score) max_score = scores[r];
        }
        for (uint32_t c = 0; c < n_comp; c++) {
            float s;
            if (use_mask && comp_mask[c] <= -5.0e29f) {
                s = -3.4e38f;
            } else {
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                s = dot * scale;
                if (use_mask) s += comp_mask[c];
            }
            scores[n_raw + c] = s;
            if (s > max_score) max_score = s;
        }

        float *oh = out_heads + (uint64_t)h * head_dim;
        memset(oh, 0, (size_t)head_dim * sizeof(float));
        float denom = expf(sinks[h] - max_score);
        for (uint32_t r = 0; r < n_raw; r++) {
            const float w = expf(scores[r] - max_score);
            denom += w;
            const uint32_t row = raw_cap ? (raw_start + r) % raw_cap : r;
            const float *kv = raw_kv + (uint64_t)row * head_dim;
            for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
        }
        for (uint32_t c = 0; c < n_comp; c++) {
            const float w = expf(scores[n_raw + c] - max_score);
            denom += w;
            const float *kv = comp_kv + (uint64_t)c * head_dim;
            for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
        }
        for (uint32_t d = 0; d < head_dim; d++) oh[d] /= denom;
    }
    free(scores);
}

/* F16 round-trip matching sycl_f32_to_f16_bits_hip_round / f16_bits_to_f32,
 * transcribed identically to the oracle already established in
 * tests/test_sycl_fp8_kv.c (dsv4-adjacent), since ds4_gpu_store_raw_kv_tensor
 * delegates to the already-tested store_raw_kv_batch_kernel path. */
static uint16_t oracle_f32_to_f16_hip_round(float f) {
    uint32_t u;
    memcpy(&u, &f, sizeof(u));
    uint32_t sign = (u >> 16) & 0x8000u;
    int32_t exp = (int32_t)((u >> 23) & 0xffu) - 127 + 15;
    uint32_t mant = u & 0x7fffffu;
    if (exp <= 0) {
        if (exp < -10) return (uint16_t)sign;
        mant |= 0x800000u;
        uint32_t shift = (uint32_t)(14 - exp);
        uint32_t half_mant = mant >> shift;
        if ((mant >> (shift - 1)) & 1u) half_mant++;
        return (uint16_t)(sign | half_mant);
    }
    if (exp >= 31) return (uint16_t)(sign | 0x7c00u);
    uint32_t half = sign | ((uint32_t)exp << 10) | (mant >> 13);
    if (mant & 0x1000u) half++;
    return (uint16_t)half;
}

static float oracle_f16_round_trip(float f) {
    return oracle_half_to_float(oracle_f32_to_f16_hip_round(f));
}

#define HEAD_DIM_KV 16u

static int test_store_raw_kv(void) {
    const uint32_t raw_cap = 8u;
    const uint32_t row = 5u;
    float kv[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) kv[d] = test_prand(1u, d, 7u) * 3.0f;

    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * HEAD_DIM_KV * sizeof(float));
    ds4_gpu_tensor *tkv = ds4_gpu_tensor_alloc((uint64_t)HEAD_DIM_KV * sizeof(float));
    CHECK(traw && tkv, "store_raw_kv: alloc failed");
    float zeros[8u * HEAD_DIM_KV];
    memset(zeros, 0, sizeof(zeros));
    CHECK(ds4_gpu_tensor_write(traw, 0, zeros, sizeof(zeros)) != 0, "store_raw_kv: zero init failed");
    CHECK(ds4_gpu_tensor_write(tkv, 0, kv, sizeof(kv)) != 0, "store_raw_kv: kv write failed");

    CHECK(ds4_gpu_store_raw_kv_tensor(traw, tkv, raw_cap, row, HEAD_DIM_KV) != 0,
          "store_raw_kv: launch failed");

    float got[8u * HEAD_DIM_KV];
    CHECK(ds4_gpu_tensor_read(traw, 0, got, sizeof(got)) != 0, "store_raw_kv: read failed");
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        CHECK_CLOSE(got[row * HEAD_DIM_KV + d], oracle_f16_round_trip(kv[d]), 1e-6,
                    "store_raw_kv: stored row mismatch");
    }
    for (uint32_t r = 0; r < raw_cap; r++) {
        if (r == row) continue;
        for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
            CHECK(got[r * HEAD_DIM_KV + d] == 0.0f, "store_raw_kv: unrelated row disturbed");
        }
    }

    CHECK(ds4_gpu_store_raw_kv_tensor(NULL, tkv, raw_cap, row, HEAD_DIM_KV) == 0,
          "store_raw_kv: null raw_cache must be rejected");
    CHECK(ds4_gpu_store_raw_kv_tensor(traw, tkv, 0u, row, HEAD_DIM_KV) == 0,
          "store_raw_kv: raw_cap == 0 must be rejected");

    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tkv);
    fprintf(stderr, "  test_store_raw_kv OK\n");
    return 0;
}

/* Oracle for the FP8 quantiser's non-RoPE scaling, transcribed from
 * dsv4_fp8_kv_quantize_row_inplace_cpu's per-block-max/scale/dequant shape
 * (ds4.c:3241-3261) and already exercised directly in
 * tests/test_sycl_fp8_kv.c; here it is only composed with the store, so the
 * test checks the composition rather than re-deriving the quantiser oracle
 * in full: the non-RoPE prefix is quantised to a single shared per-row
 * scale (max-abs over the whole n_nope prefix, since n_nope == HEAD_DIM_KV
 * fits in the quantiser's one 64-wide group), each value snapped to the
 * nearest representable E4M3 magnitude, then F16-round-tripped by the
 * store. */
static float oracle_e4m3fn_value(int code) {
    static const float exp_scale[16] = {
        0.0f, 0.015625f, 0.03125f, 0.0625f, 0.125f, 0.25f, 0.5f, 1.0f,
        2.0f, 4.0f, 8.0f, 16.0f, 32.0f, 64.0f, 128.0f, 256.0f,
    };
    const int exp = (code >> 3) & 0x0f;
    const int mant = code & 0x07;
    return exp == 0 ? (float)mant * 0.001953125f : (1.0f + (float)mant * 0.125f) * exp_scale[exp];
}

static float oracle_e4m3fn_dequant(float x) {
    const float sign = x < 0.0f ? -1.0f : 1.0f;
    const float ax = fminf(fabsf(x), 448.0f);
    int lo = 0, hi = 126;
    while (lo < hi) {
        const int mid = (lo + hi + 1) >> 1;
        if (oracle_e4m3fn_value(mid) <= ax) lo = mid; else hi = mid - 1;
    }
    int best = lo;
    if (best < 126) {
        const float best_diff = fabsf(ax - oracle_e4m3fn_value(best));
        const float next_diff = fabsf(ax - oracle_e4m3fn_value(best + 1));
        if (next_diff < best_diff || (next_diff == best_diff && ((best + 1) & 1) == 0 && (best & 1) != 0)) best++;
    }
    return sign * oracle_e4m3fn_value(best);
}

static int test_kv_fp8_store_raw(void) {
    const uint32_t raw_cap = 4u;
    const uint32_t row = 2u;
    const uint32_t n_rot = 0u; /* whole row is quantised: n_nope == head_dim */
    float kv[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) kv[d] = test_prand(2u, d, 11u) * 5.0f;

    float row_max = 1.0e-4f;
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) if (fabsf(kv[d]) > row_max) row_max = fabsf(kv[d]);
    const float scale = exp2f(ceilf(log2f(row_max / 448.0f)));
    float want[HEAD_DIM_KV];
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        const float clamped = fminf(448.0f, fmaxf(-448.0f, kv[d] / scale));
        want[d] = oracle_f16_round_trip(oracle_e4m3fn_dequant(clamped) * scale);
    }

    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * HEAD_DIM_KV * sizeof(float));
    ds4_gpu_tensor *tkv = ds4_gpu_tensor_alloc((uint64_t)HEAD_DIM_KV * sizeof(float));
    CHECK(traw && tkv, "kv_fp8_store_raw: alloc failed");
    float zeros[4u * HEAD_DIM_KV];
    memset(zeros, 0, sizeof(zeros));
    CHECK(ds4_gpu_tensor_write(traw, 0, zeros, sizeof(zeros)) != 0, "kv_fp8_store_raw: zero init failed");
    CHECK(ds4_gpu_tensor_write(tkv, 0, kv, sizeof(kv)) != 0, "kv_fp8_store_raw: kv write failed");

    CHECK(ds4_gpu_kv_fp8_store_raw_tensor(tkv, traw, raw_cap, row, HEAD_DIM_KV, n_rot) != 0,
          "kv_fp8_store_raw: launch failed");

    float got[4u * HEAD_DIM_KV];
    CHECK(ds4_gpu_tensor_read(traw, 0, got, sizeof(got)) != 0, "kv_fp8_store_raw: read failed");
    for (uint32_t d = 0; d < HEAD_DIM_KV; d++) {
        CHECK_CLOSE(got[row * HEAD_DIM_KV + d], want[d], 1e-3, "kv_fp8_store_raw: stored row mismatch");
    }

    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tkv);
    fprintf(stderr, "  test_kv_fp8_store_raw OK\n");
    return 0;
}

#define DH_N_HEAD 4u
#define DH_HEAD_DIM 16u
#define DH_N_RAW 300u
#define DH_RAW_CAP 350u
#define DH_RAW_START 300u
#define DH_N_COMP 200u

typedef struct {
    float sinks[DH_N_HEAD];
    float q[DH_N_HEAD * DH_HEAD_DIM];
    float raw_kv[DH_RAW_CAP * DH_HEAD_DIM];
    float comp_kv[DH_N_COMP * DH_HEAD_DIM];
    float comp_mask[DH_N_COMP];
} dh_fixture;

static void dh_fixture_build(dh_fixture *fx) {
    for (uint32_t h = 0; h < DH_N_HEAD; h++) fx->sinks[h] = test_prand(h, 999u, 3u) * 2.0f;
    for (uint32_t h = 0; h < DH_N_HEAD; h++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->q[h * DH_HEAD_DIM + d] = test_prand(h, d, 101u);
        }
    }
    for (uint32_t r = 0; r < DH_RAW_CAP; r++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->raw_kv[r * DH_HEAD_DIM + d] = test_prand(r, d, 202u);
        }
    }
    for (uint32_t c = 0; c < DH_N_COMP; c++) {
        for (uint32_t d = 0; d < DH_HEAD_DIM; d++) {
            fx->comp_kv[c * DH_HEAD_DIM + d] = test_prand(c, d, 303u);
        }
        fx->comp_mask[c] = 0.0f;
    }
}

/* Model buffer holding only attn_sinks, at a nonzero offset so a test that
 * accidentally reads from offset 0 (or fails to apply sinks_offset at all)
 * is caught rather than accidentally passing. */
typedef struct {
    unsigned char *bytes;
    uint64_t       size;
    uint64_t       sinks_offset;
} dh_model;

static dh_model dh_model_build(const float *sinks, uint32_t n_head) {
    dh_model m;
    m.sinks_offset = 64u;
    m.size = m.sinks_offset + (uint64_t)n_head * sizeof(float);
    m.bytes = (unsigned char *)calloc(1, (size_t)m.size);
    memcpy(m.bytes + m.sinks_offset, sinks, (size_t)n_head * sizeof(float));
    return m;
}

static int dh_run_and_check(const dh_fixture *fx, uint32_t n_raw, uint32_t raw_cap,
                            uint32_t raw_start, uint32_t n_comp, const char *what) {
    dh_model model = dh_model_build(fx->sinks, DH_N_HEAD);

    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = n_comp ? ds4_gpu_tensor_alloc((uint64_t)n_comp * DH_HEAD_DIM * sizeof(float)) : NULL;
    CHECK(theads && tq && traw && (n_comp == 0 || tcomp), "decode_heads: alloc failed");

    CHECK(ds4_gpu_tensor_write(tq, 0, fx->q, sizeof(fx->q)) != 0, "decode_heads: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx->raw_kv, (uint64_t)raw_cap * DH_HEAD_DIM * sizeof(float)) != 0,
          "decode_heads: raw_kv write failed");
    if (n_comp) {
        CHECK(ds4_gpu_tensor_write(tcomp, 0, fx->comp_kv, (uint64_t)n_comp * DH_HEAD_DIM * sizeof(float)) != 0,
              "decode_heads: comp_kv write failed");
    }

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset,
              tq, traw, n_raw, raw_cap, raw_start,
              tcomp, /*comp_kv_f16=*/0u, n_comp,
              /*comp_mask=*/NULL, /*use_mask=*/0u,
              DH_N_HEAD, DH_HEAD_DIM) != 0,
          "decode_heads: launch failed");

    float got[DH_N_HEAD * DH_HEAD_DIM];
    CHECK(ds4_gpu_tensor_read(theads, 0, got, sizeof(got)) != 0, "decode_heads: read failed");

    float want[DH_N_HEAD * DH_HEAD_DIM];
    oracle_attention_decode_heads(want, fx->sinks, fx->q, fx->raw_kv, n_raw, raw_cap, raw_start,
                                  fx->comp_kv, n_comp, NULL, 0, DH_N_HEAD, DH_HEAD_DIM);

    int rc = 0;
    for (uint32_t i = 0; i < DH_N_HEAD * DH_HEAD_DIM && rc == 0; i++) {
        char msg[96];
        snprintf(msg, sizeof(msg), "%s: heads[%u] mismatch", what, i);
        if (fabs((double)got[i] - (double)want[i]) > 1e-3) {
            fprintf(stderr, "FAIL: %s (got %.9g want %.9g)\n", msg, (double)got[i], (double)want[i]);
            rc = 1;
        }
    }

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    if (tcomp) ds4_gpu_tensor_free(tcomp);
    free(model.bytes);
    return rc;
}

static int test_decode_heads_mixed_wraparound(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    CHECK(dh_run_and_check(&fx, DH_N_RAW, DH_RAW_CAP, DH_RAW_START, DH_N_COMP,
                           "decode_heads mixed+wraparound") == 0,
          "decode_heads mixed+wraparound failed");
    fprintf(stderr, "  test_decode_heads_mixed_wraparound OK\n");
    return 0;
}

static int test_decode_heads_raw_only(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    CHECK(dh_run_and_check(&fx, DH_N_RAW, DH_RAW_CAP, DH_RAW_START, 0u,
                           "decode_heads raw-only") == 0,
          "decode_heads raw-only failed");
    fprintf(stderr, "  test_decode_heads_raw_only OK\n");
    return 0;
}

/* Validation-only cases, matching the ROCm launcher's zero-work and
 * argument-rejection shape. */
static int test_decode_heads_validation(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    dh_model model = dh_model_build(fx.sinks, DH_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)DH_RAW_CAP * DH_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw, "decode_heads validation: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, fx.q, sizeof(fx.q)) != 0, "decode_heads validation: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx.raw_kv, sizeof(fx.raw_kv)) != 0,
          "decode_heads validation: raw_kv write failed");

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              /*n_raw=*/0u, DH_RAW_CAP, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: n_raw == 0 must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, /*raw_cap=*/DH_N_RAW - 1u, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: raw_cap < n_raw must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, /*sinks_offset=*/model.size + 1u, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, NULL, 0u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: sinks_offset past model_size must be rejected");
    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, NULL, /*comp_kv_f16=*/1u, 0u, NULL, 0u,
              DH_N_HEAD, DH_HEAD_DIM) == 0,
          "decode_heads: comp_kv_f16 must be rejected");

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    free(model.bytes);
    fprintf(stderr, "  test_decode_heads_validation OK\n");
    return 0;
}

/* Cross-check within the mask-additive representation, exercised even
 * though every real ds4.c call site always passes use_mask == 0 (see the
 * file comment's oracle derivation): the ABI entry still declares this
 * parameter, so its documented behaviour is verified directly rather than
 * left untested because production never reaches it today. */
static int test_decode_heads_masked(void) {
    dh_fixture fx;
    dh_fixture_build(&fx);
    /* Disallow every third compressed row via the -1e30 sentinel; allow
     * the rest with a nonzero additive bias so the mask's two behaviours
     * (hard exclude vs. additive bias) are both exercised. */
    for (uint32_t c = 0; c < DH_N_COMP; c++) {
        fx.comp_mask[c] = (c % 3u == 0u) ? -1.0e30f : test_prand(c, 777u, 5u) * 0.5f;
    }

    dh_model model = dh_model_build(fx.sinks, DH_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)DH_N_HEAD * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)DH_RAW_CAP * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)DH_N_COMP * DH_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tmask = ds4_gpu_tensor_alloc((uint64_t)DH_N_COMP * sizeof(float));
    CHECK(theads && tq && traw && tcomp && tmask, "decode_heads masked: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, fx.q, sizeof(fx.q)) != 0, "decode_heads masked: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, fx.raw_kv, sizeof(fx.raw_kv)) != 0,
          "decode_heads masked: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, fx.comp_kv, sizeof(fx.comp_kv)) != 0,
          "decode_heads masked: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(tmask, 0, fx.comp_mask, sizeof(fx.comp_mask)) != 0,
          "decode_heads masked: mask write failed");

    CHECK(ds4_gpu_attention_decode_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              DH_N_RAW, DH_RAW_CAP, DH_RAW_START, tcomp, 0u, DH_N_COMP,
              tmask, /*use_mask=*/1u, DH_N_HEAD, DH_HEAD_DIM) != 0,
          "decode_heads masked: launch failed");

    float got[DH_N_HEAD * DH_HEAD_DIM];
    CHECK(ds4_gpu_tensor_read(theads, 0, got, sizeof(got)) != 0, "decode_heads masked: read failed");
    float want[DH_N_HEAD * DH_HEAD_DIM];
    oracle_attention_decode_heads(want, fx.sinks, fx.q, fx.raw_kv, DH_N_RAW, DH_RAW_CAP, DH_RAW_START,
                                  fx.comp_kv, DH_N_COMP, fx.comp_mask, 1, DH_N_HEAD, DH_HEAD_DIM);
    for (uint32_t i = 0; i < DH_N_HEAD * DH_HEAD_DIM; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "decode_heads masked: heads mismatch");
    }

    ds4_gpu_tensor_free(theads);
    ds4_gpu_tensor_free(tq);
    ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp);
    ds4_gpu_tensor_free(tmask);
    free(model.bytes);
    fprintf(stderr, "  test_decode_heads_masked OK\n");
    return 0;
}

/* ---- Batched decode: ds4_gpu_attention_decode_raw_batch_heads_tensor and
 * ds4_gpu_attention_decode_mixed_batch_heads_tensor -------------------------
 *
 * Oracle selection: these entries serve ds4.c's "ubatch" decode-batch path
 * (ds4.c:28609, :29353), reached when a chunk of n_tokens is decoded
 * together against an already-populated raw/compressed cache (not a
 * from-scratch prefill). Tracing that path to its CPU counterpart:
 * layer_attention_raw_swa_batch (ds4.c:13174) is the batched sibling of
 * layer_attention_raw_swa_one, and its default (non prefix_batch_attn) loop
 * pushes each token's own KV into the cache and then calls
 * layer_attention_mixed_one (ds4.c:13403) for that token using whatever the
 * cache holds at that point -- i.e. token t attends causally to every raw
 * row up to and including its own position, plus its own visible compressed
 * count. layer_attention_prefix_batch_worker (ds4.c:12840) is a DIFFERENT
 * oracle for a different call shape: it backs prefix_batch_attn, which
 * requires cache->n_raw == 0 && pos0 == 0 (a bare fresh-prompt prefill with
 * no raw history at all), not the continued-generation shape these entries
 * serve. So the oracle below unrolls layer_attention_raw_swa_batch's
 * per-token layer_attention_mixed_one calls directly: for each token t, the
 * same causal raw-window derivation the GPU kernels themselves use (mirrored
 * from attention_decode_mixed_kernel/heads8_online, read from
 * rocm/ds4_rocm_attention.cuh) picks out which raw/compressed rows are
 * visible, then layer_attention_mixed_one's per-head softmax math is applied
 * to just those rows.
 *
 * Differential cross-check: use_comp_mask forces the general kernel even at
 * head_dim == 512 (the online path requires !use_comp_mask), so the same
 * head_dim == 512, n_tokens > 1 shape is run twice -- once with
 * use_comp_mask == 0 (online kernel) and once with use_comp_mask == 1 and an
 * all-zero mask (general kernel, mathematically identical to no mask at
 * all) -- and the two outputs are compared directly as well as against the
 * oracle, since a differential between two real
 * paths catches drift an oracle comparison alone can miss. */

static void oracle_attention_decode_batch(
        float *out_heads, const float *sinks, const float *q,
        const float *raw_kv, uint32_t n_tokens, uint32_t pos0, uint32_t n_raw,
        uint32_t raw_cap, uint32_t raw_start, const float *comp_kv, uint32_t n_comp,
        uint32_t window, uint32_t ratio, uint32_t n_head, uint32_t head_dim) {
    const float scale = 1.0f / sqrtf((float)head_dim);
    const bool single_all = (n_tokens == 1u && ratio == 0u);
    const uint32_t first_raw_pos = pos0 + n_tokens - n_raw;
    float *scores = (float *)malloc((size_t)(256u + n_comp + 1u) * sizeof(float));

    for (uint32_t t = 0; t < n_tokens; t++) {
        const uint32_t qpos = pos0 + t;
        uint32_t visible_comp = single_all ? n_comp : (n_comp ? (qpos + 1u) / ratio : 0u);
        if (visible_comp > n_comp) visible_comp = n_comp;

        uint32_t raw_count = 0u, raw_first_idx = 0u;
        if (n_raw != 0u) {
            const uint32_t raw_last_pos = first_raw_pos + n_raw - 1u;
            if (single_all) {
                raw_count = n_raw > 256u ? 256u : n_raw;
            } else if (qpos >= first_raw_pos) {
                uint32_t lo = first_raw_pos;
                if (window != 0u && qpos + 1u > window) {
                    const uint32_t wlo = qpos + 1u - window;
                    if (wlo > lo) lo = wlo;
                }
                const uint32_t hi = qpos < raw_last_pos ? qpos : raw_last_pos;
                if (hi >= lo) {
                    raw_first_idx = lo - first_raw_pos;
                    raw_count = hi - lo + 1u;
                    if (raw_count > 256u) raw_count = 256u;
                }
            }
        }

        for (uint32_t h = 0; h < n_head; h++) {
            const float *qh = q + ((uint64_t)t * n_head + h) * head_dim;
            float max_score = sinks[h];
            for (uint32_t r = 0; r < raw_count; r++) {
                const uint32_t row = (raw_start + raw_first_idx + r) % raw_cap;
                const float *kv = raw_kv + (uint64_t)row * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[r] = dot * scale;
                if (scores[r] > max_score) max_score = scores[r];
            }
            for (uint32_t c = 0; c < visible_comp; c++) {
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[raw_count + c] = dot * scale;
                if (scores[raw_count + c] > max_score) max_score = scores[raw_count + c];
            }

            float *oh = out_heads + ((uint64_t)t * n_head + h) * head_dim;
            memset(oh, 0, (size_t)head_dim * sizeof(float));
            float denom = expf(sinks[h] - max_score);
            for (uint32_t r = 0; r < raw_count; r++) {
                const float w = expf(scores[r] - max_score);
                denom += w;
                const uint32_t row = (raw_start + raw_first_idx + r) % raw_cap;
                const float *kv = raw_kv + (uint64_t)row * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t c = 0; c < visible_comp; c++) {
                const float w = expf(scores[raw_count + c] - max_score);
                denom += w;
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t d = 0; d < head_dim; d++) oh[d] /= denom;
        }
    }
    free(scores);
}

#define SB_N_HEAD 4u
#define SB_HEAD_DIM 16u
#define SB_N_TOKENS 6u
#define SB_POS0 40u
#define SB_N_RAW 50u
#define SB_RAW_CAP 64u
#define SB_RAW_START 20u
#define SB_WINDOW 12u
#define SB_N_COMP 30u
#define SB_RATIO 3u

static int test_decode_raw_batch_small(void) {
    float sinks[SB_N_HEAD];
    for (uint32_t h = 0; h < SB_N_HEAD; h++) sinks[h] = test_prand(h, 11u, 1u) * 2.0f;
    float *q = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    float *raw_kv = malloc((size_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float));
    for (uint32_t i = 0; i < SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM; i++) q[i] = test_prand(i, 51u, 2u);
    for (uint32_t i = 0; i < SB_RAW_CAP * SB_HEAD_DIM; i++) raw_kv[i] = test_prand(i, 52u, 3u);

    dh_model model = dh_model_build(sinks, SB_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw, "decode_raw_batch small: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, (uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_raw_batch small: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, (uint64_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_raw_batch small: raw_kv write failed");

    CHECK(ds4_gpu_attention_decode_raw_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              SB_N_TOKENS, SB_POS0, SB_N_RAW, SB_RAW_CAP, SB_RAW_START, SB_WINDOW,
              SB_N_HEAD, SB_HEAD_DIM) != 0,
          "decode_raw_batch small: launch failed");

    float *got = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, (uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_raw_batch small: read failed");
    float *want = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    oracle_attention_decode_batch(want, sinks, q, raw_kv, SB_N_TOKENS, SB_POS0, SB_N_RAW,
                                  SB_RAW_CAP, SB_RAW_START, NULL, 0u, SB_WINDOW, 1u,
                                  SB_N_HEAD, SB_HEAD_DIM);
    for (uint32_t i = 0; i < SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "decode_raw_batch small: heads mismatch");
    }

    free(q); free(raw_kv); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    fprintf(stderr, "  test_decode_raw_batch_small OK\n");
    return 0;
}

static int test_decode_mixed_batch_small(void) {
    float sinks[SB_N_HEAD];
    for (uint32_t h = 0; h < SB_N_HEAD; h++) sinks[h] = test_prand(h, 21u, 4u) * 2.0f;
    float *q = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    float *raw_kv = malloc((size_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float));
    float *comp_kv = malloc((size_t)SB_N_COMP * SB_HEAD_DIM * sizeof(float));
    for (uint32_t i = 0; i < SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM; i++) q[i] = test_prand(i, 61u, 5u);
    for (uint32_t i = 0; i < SB_RAW_CAP * SB_HEAD_DIM; i++) raw_kv[i] = test_prand(i, 62u, 6u);
    for (uint32_t i = 0; i < SB_N_COMP * SB_HEAD_DIM; i++) comp_kv[i] = test_prand(i, 63u, 7u);

    dh_model model = dh_model_build(sinks, SB_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)SB_N_COMP * SB_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw && tcomp, "decode_mixed_batch small: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, (uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_mixed_batch small: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, (uint64_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_mixed_batch small: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, (uint64_t)SB_N_COMP * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_mixed_batch small: comp_kv write failed");

    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp,
              /*comp_kv_f16=*/0u, /*comp_mask=*/NULL, /*use_comp_mask=*/0u,
              SB_N_TOKENS, SB_POS0, SB_N_RAW, SB_RAW_CAP, SB_RAW_START, SB_N_COMP,
              SB_WINDOW, SB_RATIO, SB_N_HEAD, SB_HEAD_DIM) != 0,
          "decode_mixed_batch small: launch failed");

    float *got = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, (uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float)) != 0,
          "decode_mixed_batch small: read failed");
    float *want = malloc((size_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    oracle_attention_decode_batch(want, sinks, q, raw_kv, SB_N_TOKENS, SB_POS0, SB_N_RAW,
                                  SB_RAW_CAP, SB_RAW_START, comp_kv, SB_N_COMP, SB_WINDOW,
                                  SB_RATIO, SB_N_HEAD, SB_HEAD_DIM);
    for (uint32_t i = 0; i < SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "decode_mixed_batch small: heads mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp);
    fprintf(stderr, "  test_decode_mixed_batch_small OK\n");
    return 0;
}

#define OL_N_HEAD 3u
#define OL_HEAD_DIM 512u
#define OL_N_TOKENS 5u
#define OL_POS0 90u
#define OL_N_RAW 70u
#define OL_RAW_CAP 96u
#define OL_RAW_START 40u
#define OL_WINDOW 20u
#define OL_N_COMP 25u
#define OL_RATIO 2u

static int test_decode_mixed_batch_online_vs_general(void) {
    float sinks[OL_N_HEAD];
    for (uint32_t h = 0; h < OL_N_HEAD; h++) sinks[h] = test_prand(h, 71u, 8u) * 2.0f;
    const uint64_t qn = (uint64_t)OL_N_TOKENS * OL_N_HEAD * OL_HEAD_DIM;
    const uint64_t rawn = (uint64_t)OL_RAW_CAP * OL_HEAD_DIM;
    const uint64_t compn = (uint64_t)OL_N_COMP * OL_HEAD_DIM;
    float *q = malloc((size_t)qn * sizeof(float));
    float *raw_kv = malloc((size_t)rawn * sizeof(float));
    float *comp_kv = malloc((size_t)compn * sizeof(float));
    for (uint64_t i = 0; i < qn; i++) q[i] = test_prand((uint32_t)i, 81u, 9u);
    for (uint64_t i = 0; i < rawn; i++) raw_kv[i] = test_prand((uint32_t)i, 82u, 10u);
    for (uint64_t i = 0; i < compn; i++) comp_kv[i] = test_prand((uint32_t)i, 83u, 11u);
    float *zero_mask = calloc((size_t)OL_N_TOKENS * OL_N_COMP, sizeof(float));

    dh_model model = dh_model_build(sinks, OL_N_HEAD);
    ds4_gpu_tensor *theads_online = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *theads_general = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc(rawn * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc(compn * sizeof(float));
    ds4_gpu_tensor *tmask = ds4_gpu_tensor_alloc((uint64_t)OL_N_TOKENS * OL_N_COMP * sizeof(float));
    CHECK(theads_online && theads_general && tq && traw && tcomp && tmask,
          "decode_mixed_batch online/general: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, qn * sizeof(float)) != 0, "online/general: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, rawn * sizeof(float)) != 0, "online/general: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, compn * sizeof(float)) != 0, "online/general: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(tmask, 0, zero_mask, (uint64_t)OL_N_TOKENS * OL_N_COMP * sizeof(float)) != 0,
          "online/general: mask write failed");

    /* use_comp_mask == 0: takes the head_dim == 512 online kernel. */
    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads_online, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp,
              0u, NULL, /*use_comp_mask=*/0u,
              OL_N_TOKENS, OL_POS0, OL_N_RAW, OL_RAW_CAP, OL_RAW_START, OL_N_COMP,
              OL_WINDOW, OL_RATIO, OL_N_HEAD, OL_HEAD_DIM) != 0,
          "online/general: online launch failed");
    /* use_comp_mask == 1 with an all-zero mask: same math, forced onto the
     * general scalar kernel since the online path requires !use_comp_mask. */
    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads_general, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp,
              0u, tmask, /*use_comp_mask=*/1u,
              OL_N_TOKENS, OL_POS0, OL_N_RAW, OL_RAW_CAP, OL_RAW_START, OL_N_COMP,
              OL_WINDOW, OL_RATIO, OL_N_HEAD, OL_HEAD_DIM) != 0,
          "online/general: general launch failed");

    float *got_online = malloc((size_t)qn * sizeof(float));
    float *got_general = malloc((size_t)qn * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads_online, 0, got_online, qn * sizeof(float)) != 0,
          "online/general: online read failed");
    CHECK(ds4_gpu_tensor_read(theads_general, 0, got_general, qn * sizeof(float)) != 0,
          "online/general: general read failed");

    float *want = malloc((size_t)qn * sizeof(float));
    oracle_attention_decode_batch(want, sinks, q, raw_kv, OL_N_TOKENS, OL_POS0, OL_N_RAW,
                                  OL_RAW_CAP, OL_RAW_START, comp_kv, OL_N_COMP, OL_WINDOW,
                                  OL_RATIO, OL_N_HEAD, OL_HEAD_DIM);

    for (uint64_t i = 0; i < qn; i++) {
        CHECK_CLOSE(got_online[i], want[i], 1e-3, "online/general: online vs oracle mismatch");
        CHECK_CLOSE(got_general[i], want[i], 1e-3, "online/general: general vs oracle mismatch");
        CHECK_CLOSE(got_online[i], got_general[i], 1e-3, "online/general: online vs general differential mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(zero_mask);
    free(got_online); free(got_general); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads_online); ds4_gpu_tensor_free(theads_general);
    ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw); ds4_gpu_tensor_free(tcomp);
    ds4_gpu_tensor_free(tmask);
    fprintf(stderr, "  test_decode_mixed_batch_online_vs_general OK\n");
    return 0;
}

/* Targets the online kernel's running-max-across-tiles specifically: max
 * subtraction is a numerical-stability device that is invisible in exact
 * arithmetic (softmax is invariant to subtracting any constant, correct or
 * not, from every scored position uniformly, per spec 6f), so a moderate
 * score spread cannot discriminate a broken running max from a correct one
 * -- both stay comfortably inside float range and normalise to the same
 * ratios. This test instead makes one raw row's score enormous (a raw KV
 * row set to a large constant magnitude against a consistently-signed Q,
 * guaranteeing a large positive dot product) and places it in an EARLY
 * 4-row tile while every other row stays near zero magnitude, so a kernel
 * that fails to carry the running
 * maximum across tiles ends its max-only pass holding only the LAST tile's
 * (tiny) score. exp(huge_score - tiny_wrong_max) then overflows to
 * infinity in the second pass; the correct running max keeps every
 * exponent near zero and the result finite, close to the loud row itself
 * (its softmax weight dominates all others by many orders of magnitude). */
static int test_decode_mixed_batch_online_running_max(void) {
    /* n_tokens must be > 1: the batch launcher only ever reaches the online
     * kernel for head_dim == 512 when n_tokens > 1 (or when n_comp exceeds
     * the general kernel's score-buffer cap, not exercised here); a
     * single-token call at a small n_comp takes the general scalar kernel
     * instead, per sycl_attention_decode_batch_launch's branch order. */
    const uint32_t n_head = 1u, head_dim = 512u, n_tokens = 2u;
    const uint32_t n_raw = 21u, raw_cap = 21u, raw_start = 0u;
    const uint32_t loud_row = 2u; /* inside the first 4-row tile */
    const uint32_t pos0 = n_raw - n_tokens;

    float sinks[1] = {0.0f};
    float *q = malloc((size_t)n_tokens * head_dim * sizeof(float));
    float *raw_kv = malloc((size_t)raw_cap * head_dim * sizeof(float));
    /* A small positive bias, not a zero-mean random value: the loud row
     * below is a large CONSTANT rather than a multiple of Q, so its dot
     * product with Q is only reliably large if Q's components are
     * consistently signed. */
    for (uint32_t t = 0; t < n_tokens; t++) {
        for (uint32_t d = 0; d < head_dim; d++) {
            q[t * head_dim + d] = 0.05f + test_prand(t, d, 12u) * 0.02f;
        }
    }
    for (uint32_t r = 0; r < raw_cap; r++) {
        for (uint32_t d = 0; d < head_dim; d++) {
            raw_kv[r * head_dim + d] = (r == loud_row) ? 4000.0f
                                                        : test_prand(r, d, 93u) * 0.3f;
        }
    }

    dh_model model = dh_model_build(sinks, n_head);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)n_tokens * n_head * head_dim * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)n_tokens * n_head * head_dim * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)raw_cap * head_dim * sizeof(float));
    CHECK(theads && tq && traw, "online running max: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, (uint64_t)n_tokens * head_dim * sizeof(float)) != 0,
          "online running max: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, (uint64_t)raw_cap * head_dim * sizeof(float)) != 0,
          "online running max: raw_kv write failed");

    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, NULL,
              0u, NULL, /*use_comp_mask=*/0u, n_tokens, pos0, n_raw, raw_cap, raw_start,
              /*n_comp=*/0u, /*window=*/0u, /*ratio=*/1u, n_head, head_dim) != 0,
          "online running max: launch failed");

    float *got = malloc((size_t)n_tokens * head_dim * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, (uint64_t)n_tokens * head_dim * sizeof(float)) != 0,
          "online running max: read failed");
    float *want = malloc((size_t)n_tokens * head_dim * sizeof(float));
    oracle_attention_decode_batch(want, sinks, q, raw_kv, n_tokens, pos0, n_raw, raw_cap,
                                  raw_start, NULL, 0u, 0u, 1u, n_head, head_dim);

    for (uint32_t i = 0; i < n_tokens * head_dim; i++) {
        const uint32_t d = i % head_dim;
        CHECK(isfinite(got[i]), "online running max: got a non-finite value");
        CHECK_CLOSE(got[i], want[i], 1e-2, "online running max: heads mismatch");
        /* The loud row's weight should dominate to the point that the
         * output is nearly identical to that row itself. */
        CHECK_CLOSE(got[i], raw_kv[loud_row * head_dim + d], 5e-2,
                    "online running max: output not dominated by the loud row");
    }

    free(q); free(raw_kv); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    fprintf(stderr, "  test_decode_mixed_batch_online_running_max OK\n");
    return 0;
}

static int test_decode_batch_validation(void) {
    float sinks[SB_N_HEAD] = {0};
    dh_model model = dh_model_build(sinks, SB_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)SB_N_TOKENS * SB_N_HEAD * SB_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)SB_RAW_CAP * SB_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw, "decode_batch validation: alloc failed");

    CHECK(ds4_gpu_attention_decode_raw_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw,
              /*n_tokens=*/0u, SB_POS0, SB_N_RAW, SB_RAW_CAP, SB_RAW_START, SB_WINDOW,
              SB_N_HEAD, SB_HEAD_DIM) == 0,
          "decode_batch: n_tokens == 0 must be rejected");
    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, NULL,
              /*comp_kv_f16=*/1u, NULL, 0u, SB_N_TOKENS, SB_POS0, SB_N_RAW, SB_RAW_CAP,
              SB_RAW_START, 0u, SB_WINDOW, 1u, SB_N_HEAD, SB_HEAD_DIM) == 0,
          "decode_batch: comp_kv_f16 must be rejected");
    CHECK(ds4_gpu_attention_decode_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, NULL,
              0u, NULL, 0u, SB_N_TOKENS, SB_POS0, SB_N_RAW, SB_RAW_CAP, SB_RAW_START,
              /*n_comp=*/5u, SB_WINDOW, /*ratio=*/0u, SB_N_HEAD, SB_HEAD_DIM) == 0,
          "decode_batch: n_comp != 0 with ratio == 0 must be rejected");

    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    free(model.bytes);
    fprintf(stderr, "  test_decode_batch_validation OK\n");
    return 0;
}

/* ---- Indexed decode and small-window static prefill --------------------
 *
 * Oracle: ds4_gpu_attention_indexed_mixed_batch_heads_tensor's per-(t,h)
 * math is identical to the mixed (non-indexed) decode oracle above --
 * layer_attention_mixed_one's raw+comp softmax -- with one difference: the
 * set of visible compressed rows is whatever the topk list selects (capped
 * at 1024 and at `visible_comp`), rather than every row below
 * `visible_comp`. ds4.c has no CPU function that consumes a raw int32 topk
 * array directly (indexer_allowed_decode_one instead produces a boolean
 * allowed mask consumed by layer_attention_mixed_one's comp_allowed
 * parameter), so the oracle below is this file's own transcription of the
 * GPU kernels' shared math (attention_indexed_mixed_kernel and
 * attention_indexed_mixed_heads8_online_kernel, rocm/ds4_rocm_attention.cuh),
 * read directly rather than assumed, combined with layer_attention_mixed_one's
 * already-established softmax shape. */

static void oracle_attention_indexed_batch(
        float *out_heads, const float *sinks, const float *q, const float *raw_kv,
        uint32_t n_tokens, uint32_t pos0, uint32_t n_raw, uint32_t raw_cap,
        uint32_t raw_start, const float *comp_kv, uint32_t n_comp, const int32_t *topk,
        uint32_t top_k, uint32_t window, uint32_t ratio, uint32_t n_head, uint32_t head_dim) {
    const float scale = 1.0f / sqrtf((float)head_dim);
    const uint32_t first_raw_pos = pos0 + n_tokens - n_raw;
    uint32_t *comp_rows = (uint32_t *)malloc(1024u * sizeof(uint32_t));
    float *scores = (float *)malloc((size_t)(256u + 1024u + 1u) * sizeof(float));

    for (uint32_t t = 0; t < n_tokens; t++) {
        const uint32_t qpos = pos0 + t;
        uint32_t visible_comp = n_comp;
        if (ratio != 0u) {
            visible_comp = (qpos + 1u) / ratio;
            if (visible_comp > n_comp) visible_comp = n_comp;
        }
        uint32_t raw_count = 0u, raw_first_idx = 0u;
        if (n_raw != 0u) {
            const uint32_t raw_last_pos = first_raw_pos + n_raw - 1u;
            if (qpos >= first_raw_pos) {
                uint32_t lo = first_raw_pos;
                if (window != 0u && qpos + 1u > window) {
                    const uint32_t wlo = qpos + 1u - window;
                    if (wlo > lo) lo = wlo;
                }
                const uint32_t hi = qpos < raw_last_pos ? qpos : raw_last_pos;
                if (hi >= lo) {
                    raw_first_idx = lo - first_raw_pos;
                    raw_count = hi - lo + 1u;
                    if (raw_count > 256u) raw_count = 256u;
                }
            }
        }
        uint32_t comp_count = 0u;
        for (uint32_t i = 0; i < top_k && comp_count < 1024u; i++) {
            const int32_t ci = topk[(uint64_t)t * top_k + i];
            if (ci >= 0 && (uint32_t)ci < visible_comp) comp_rows[comp_count++] = (uint32_t)ci;
        }

        for (uint32_t h = 0; h < n_head; h++) {
            const float *qh = q + ((uint64_t)t * n_head + h) * head_dim;
            float max_score = sinks[h];
            for (uint32_t r = 0; r < raw_count; r++) {
                const uint32_t row = (raw_start + raw_first_idx + r) % raw_cap;
                const float *kv = raw_kv + (uint64_t)row * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[r] = dot * scale;
                if (scores[r] > max_score) max_score = scores[r];
            }
            for (uint32_t c = 0; c < comp_count; c++) {
                const float *kv = comp_kv + (uint64_t)comp_rows[c] * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[raw_count + c] = dot * scale;
                if (scores[raw_count + c] > max_score) max_score = scores[raw_count + c];
            }

            float *oh = out_heads + ((uint64_t)t * n_head + h) * head_dim;
            memset(oh, 0, (size_t)head_dim * sizeof(float));
            float denom = expf(sinks[h] - max_score);
            for (uint32_t r = 0; r < raw_count; r++) {
                const float w = expf(scores[r] - max_score);
                denom += w;
                const uint32_t row = (raw_start + raw_first_idx + r) % raw_cap;
                const float *kv = raw_kv + (uint64_t)row * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t c = 0; c < comp_count; c++) {
                const float w = expf(scores[raw_count + c] - max_score);
                denom += w;
                const float *kv = comp_kv + (uint64_t)comp_rows[c] * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t d = 0; d < head_dim; d++) oh[d] /= denom;
        }
    }
    free(comp_rows);
    free(scores);
}

/* Fills a top_k-wide topk row per token with a pseudo-random SUBSET of
 * [0, n_comp): distinct indices, so the selection is a genuine strict
 * subset whenever top_k < visible n_comp, which is what makes the "ignore
 * the index list" ablation observable. Padded with -1 sentinels past
 * n_selected, matching the indexer's own real output shape. */
static void fill_topk_subset(int32_t *topk, uint32_t n_tokens, uint32_t top_k,
                             uint32_t n_comp, uint32_t n_selected, uint32_t seed) {
    for (uint32_t t = 0; t < n_tokens; t++) {
        int32_t *row = topk + (uint64_t)t * top_k;
        for (uint32_t i = 0; i < top_k; i++) row[i] = -1;
        uint32_t placed = 0;
        uint32_t start = (uint32_t)(test_prand(t, seed, 1u) * 0.5f * (float)n_comp) + n_comp;
        for (uint32_t k = 0; k < n_comp && placed < n_selected; k++) {
            const uint32_t c = (start + k * 7u + 3u) % n_comp;
            bool dup = false;
            for (uint32_t j = 0; j < placed; j++) {
                if (row[j] == (int32_t)c) { dup = true; break; }
            }
            if (!dup) row[placed++] = (int32_t)c;
        }
    }
}

#define IX_N_HEAD 3u
#define IX_HEAD_DIM 16u
#define IX_N_TOKENS 4u
#define IX_POS0 60u
#define IX_N_RAW 40u
#define IX_RAW_CAP 48u
#define IX_RAW_START 10u
#define IX_WINDOW 15u
#define IX_N_COMP 60u
#define IX_TOP_K 8u
#define IX_N_SELECTED 5u
#define IX_RATIO 2u

static int test_indexed_mixed_general(void) {
    float sinks[IX_N_HEAD];
    for (uint32_t h = 0; h < IX_N_HEAD; h++) sinks[h] = test_prand(h, 111u, 1u) * 2.0f;
    float *q = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    float *raw_kv = malloc((size_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float));
    float *comp_kv = malloc((size_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float));
    int32_t *topk = malloc((size_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t));
    for (uint32_t i = 0; i < IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM; i++) q[i] = test_prand(i, 112u, 2u);
    for (uint32_t i = 0; i < IX_RAW_CAP * IX_HEAD_DIM; i++) raw_kv[i] = test_prand(i, 113u, 3u);
    for (uint32_t i = 0; i < IX_N_COMP * IX_HEAD_DIM; i++) comp_kv[i] = test_prand(i, 114u, 4u);
    fill_topk_subset(topk, IX_N_TOKENS, IX_TOP_K, IX_N_COMP, IX_N_SELECTED, 115u);

    dh_model model = dh_model_build(sinks, IX_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *ttopk = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t));
    CHECK(theads && tq && traw && tcomp && ttopk, "indexed general: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, (uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed general: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, (uint64_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed general: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, (uint64_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed general: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(ttopk, 0, topk, (uint64_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t)) != 0,
          "indexed general: topk write failed");

    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              ttopk, IX_N_TOKENS, IX_POS0, IX_N_RAW, IX_RAW_CAP, IX_RAW_START, IX_N_COMP,
              IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM) != 0,
          "indexed general: launch failed");

    float *got = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, (uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed general: read failed");
    float *want = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    oracle_attention_indexed_batch(want, sinks, q, raw_kv, IX_N_TOKENS, IX_POS0, IX_N_RAW,
                                   IX_RAW_CAP, IX_RAW_START, comp_kv, IX_N_COMP, topk,
                                   IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM);
    for (uint32_t i = 0; i < IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "indexed general: heads mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(topk); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp); ds4_gpu_tensor_free(ttopk);
    fprintf(stderr, "  test_indexed_mixed_general OK\n");
    return 0;
}

#define IXO_N_HEAD 20u
#define IXO_HEAD_DIM 512u
#define IXO_N_TOKENS 3u
#define IXO_POS0 30u
#define IXO_N_RAW 25u
#define IXO_RAW_CAP 32u
#define IXO_RAW_START 5u
#define IXO_WINDOW 10u
#define IXO_N_COMP 40u
#define IXO_N_SELECTED 6u
#define IXO_RATIO 2u

/* Runs the head_dim == 512 online path at the given top_k (64: the plain
 * online kernel; 512: forces the indexed_topk_sort_512_asc_kernel path
 * first, since n_tokens > 1 && top_k == 512, this is the first consumer of
 * that sort kernel) and checks against the oracle. n_head == 20 spans
 * more than one 16-head work-group (grid_y = ceil(20/16) = 2), exercising
 * the second, partially-empty group. */
static int test_indexed_mixed_online(uint32_t top_k) {
    float sinks[IXO_N_HEAD];
    for (uint32_t h = 0; h < IXO_N_HEAD; h++) sinks[h] = test_prand(h, 121u, 5u) * 2.0f;
    const uint64_t qn = (uint64_t)IXO_N_TOKENS * IXO_N_HEAD * IXO_HEAD_DIM;
    const uint64_t rawn = (uint64_t)IXO_RAW_CAP * IXO_HEAD_DIM;
    const uint64_t compn = (uint64_t)IXO_N_COMP * IXO_HEAD_DIM;
    float *q = malloc((size_t)qn * sizeof(float));
    float *raw_kv = malloc((size_t)rawn * sizeof(float));
    float *comp_kv = malloc((size_t)compn * sizeof(float));
    int32_t *topk = malloc((size_t)IXO_N_TOKENS * top_k * sizeof(int32_t));
    for (uint64_t i = 0; i < qn; i++) q[i] = test_prand((uint32_t)i, 122u, 6u);
    for (uint64_t i = 0; i < rawn; i++) raw_kv[i] = test_prand((uint32_t)i, 123u, 7u);
    for (uint64_t i = 0; i < compn; i++) comp_kv[i] = test_prand((uint32_t)i, 124u, 8u);
    fill_topk_subset(topk, IXO_N_TOKENS, top_k, IXO_N_COMP, IXO_N_SELECTED, 125u);

    dh_model model = dh_model_build(sinks, IXO_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc(rawn * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc(compn * sizeof(float));
    ds4_gpu_tensor *ttopk = ds4_gpu_tensor_alloc((uint64_t)IXO_N_TOKENS * top_k * sizeof(int32_t));
    CHECK(theads && tq && traw && tcomp && ttopk, "indexed online: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, qn * sizeof(float)) != 0, "indexed online: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, rawn * sizeof(float)) != 0, "indexed online: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, compn * sizeof(float)) != 0, "indexed online: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(ttopk, 0, topk, (uint64_t)IXO_N_TOKENS * top_k * sizeof(int32_t)) != 0,
          "indexed online: topk write failed");

    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              ttopk, IXO_N_TOKENS, IXO_POS0, IXO_N_RAW, IXO_RAW_CAP, IXO_RAW_START, IXO_N_COMP,
              top_k, IXO_WINDOW, IXO_RATIO, IXO_N_HEAD, IXO_HEAD_DIM) != 0,
          "indexed online: launch failed");

    float *got = malloc((size_t)qn * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, qn * sizeof(float)) != 0, "indexed online: read failed");
    float *want = malloc((size_t)qn * sizeof(float));
    oracle_attention_indexed_batch(want, sinks, q, raw_kv, IXO_N_TOKENS, IXO_POS0, IXO_N_RAW,
                                   IXO_RAW_CAP, IXO_RAW_START, comp_kv, IXO_N_COMP, topk,
                                   top_k, IXO_WINDOW, IXO_RATIO, IXO_N_HEAD, IXO_HEAD_DIM);
    for (uint64_t i = 0; i < qn; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "indexed online: heads mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(topk); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp); ds4_gpu_tensor_free(ttopk);
    fprintf(stderr, "  test_indexed_mixed_online(top_k=%u) OK\n", top_k);
    return 0;
}

/* Index list entry out of range: one selected index is deliberately
 * n_comp + 3 (past the end of the compressed cache), which the kernels
 * must skip via their `c < n_comp` bounds check rather than reading past
 * comp_kv. Constructed as a normal (non-ablated) test: the correct
 * production code must handle this input gracefully, since a real topk
 * tensor is a device buffer this entry does not otherwise validate
 * per-element. */
static int test_indexed_mixed_out_of_range_index(void) {
    float sinks[IX_N_HEAD];
    for (uint32_t h = 0; h < IX_N_HEAD; h++) sinks[h] = test_prand(h, 131u, 9u) * 2.0f;
    float *q = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    float *raw_kv = malloc((size_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float));
    float *comp_kv = malloc((size_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float));
    int32_t *topk = malloc((size_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t));
    for (uint32_t i = 0; i < IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM; i++) q[i] = test_prand(i, 132u, 10u);
    for (uint32_t i = 0; i < IX_RAW_CAP * IX_HEAD_DIM; i++) raw_kv[i] = test_prand(i, 133u, 11u);
    for (uint32_t i = 0; i < IX_N_COMP * IX_HEAD_DIM; i++) comp_kv[i] = test_prand(i, 134u, 12u);
    fill_topk_subset(topk, IX_N_TOKENS, IX_TOP_K, IX_N_COMP, IX_N_SELECTED, 135u);
    /* Corrupt one selected slot per token to an out-of-range index. */
    for (uint32_t t = 0; t < IX_N_TOKENS; t++) topk[t * IX_TOP_K + 0] = (int32_t)(IX_N_COMP + 3u);

    dh_model model = dh_model_build(sinks, IX_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *ttopk = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t));
    CHECK(theads && tq && traw && tcomp && ttopk, "indexed oor: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, (uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed oor: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, (uint64_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed oor: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, (uint64_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed oor: comp_kv write failed");
    CHECK(ds4_gpu_tensor_write(ttopk, 0, topk, (uint64_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t)) != 0,
          "indexed oor: topk write failed");

    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              ttopk, IX_N_TOKENS, IX_POS0, IX_N_RAW, IX_RAW_CAP, IX_RAW_START, IX_N_COMP,
              IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM) != 0,
          "indexed oor: launch failed");

    float *got = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, (uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float)) != 0,
          "indexed oor: read failed");
    float *want = malloc((size_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    oracle_attention_indexed_batch(want, sinks, q, raw_kv, IX_N_TOKENS, IX_POS0, IX_N_RAW,
                                   IX_RAW_CAP, IX_RAW_START, comp_kv, IX_N_COMP, topk,
                                   IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM);
    for (uint32_t i = 0; i < IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM; i++) {
        CHECK(isfinite(got[i]), "indexed oor: got a non-finite value");
        CHECK_CLOSE(got[i], want[i], 1e-3, "indexed oor: heads mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(topk); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp); ds4_gpu_tensor_free(ttopk);
    fprintf(stderr, "  test_indexed_mixed_out_of_range_index OK\n");
    return 0;
}

static int test_indexed_batch_validation(void) {
    float sinks[IX_N_HEAD] = {0};
    dh_model model = dh_model_build(sinks, IX_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_N_HEAD * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)IX_RAW_CAP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)IX_N_COMP * IX_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *ttopk = ds4_gpu_tensor_alloc((uint64_t)IX_N_TOKENS * IX_TOP_K * sizeof(int32_t));
    CHECK(theads && tq && traw && tcomp && ttopk, "indexed validation: alloc failed");

    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, /*comp_kv_f16=*/1u,
              ttopk, IX_N_TOKENS, IX_POS0, IX_N_RAW, IX_RAW_CAP, IX_RAW_START, IX_N_COMP,
              IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM) == 0,
          "indexed validation: comp_kv_f16 must be rejected");
    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              ttopk, IX_N_TOKENS, IX_POS0, IX_N_RAW, IX_RAW_CAP, IX_RAW_START, /*n_comp=*/0u,
              IX_TOP_K, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM) == 0,
          "indexed validation: n_comp == 0 must be rejected");
    CHECK(ds4_gpu_attention_indexed_mixed_batch_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              ttopk, IX_N_TOKENS, IX_POS0, IX_N_RAW, IX_RAW_CAP, IX_RAW_START, IX_N_COMP,
              /*top_k=*/1025u, IX_WINDOW, IX_RATIO, IX_N_HEAD, IX_HEAD_DIM) == 0,
          "indexed validation: top_k above cap must be rejected");

    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp); ds4_gpu_tensor_free(ttopk);
    free(model.bytes);
    fprintf(stderr, "  test_indexed_batch_validation OK\n");
    return 0;
}

/* ---- Small-window static prefill ---------------------------------------
 *
 * Oracle: layer_attention_prefix_batch_worker's math (ds4.c:12840-12897)
 * specialised to the non-indexed, unmasked shape this entry serves --
 * raw_count derived from `t + 1` capped at a window bound, comp visibility
 * from `ratio` alone, no allowed-bits mask -- read directly against
 * attention_static_mixed_heads8_online_kernel's own raw_count/comp_count
 * derivation (rocm/ds4_rocm_attention.cuh:1288-1294), which is identical:
 * both derive `raw_count = window && t+1 > window ? window : t+1` from the
 * token's LOCAL prefix index `t`, not an absolute position, since this
 * entry has no pos0 parameter (a fresh prefill chunk always starts at
 * position 0). */
static void oracle_attention_static_prefill(
        float *out_heads, const float *sinks, const float *q, const float *raw_kv,
        uint32_t n_tokens, const float *comp_kv, uint32_t n_comp, uint32_t window,
        uint32_t ratio, uint32_t n_head, uint32_t head_dim) {
    const float scale = 1.0f / sqrtf((float)head_dim);
    float *scores = (float *)malloc((size_t)(768u + 1u) * sizeof(float));
    for (uint32_t t = 0; t < n_tokens; t++) {
        const uint32_t raw_count = (window != 0u && t + 1u > window) ? window : t + 1u;
        const uint32_t raw_start = t + 1u - raw_count;
        uint32_t comp_count = 0u;
        if (n_comp != 0u && ratio != 0u) {
            comp_count = (t + 1u) / ratio;
            if (comp_count > n_comp) comp_count = n_comp;
        }
        for (uint32_t h = 0; h < n_head; h++) {
            const float *qh = q + ((uint64_t)t * n_head + h) * head_dim;
            float max_score = sinks[h];
            for (uint32_t r = 0; r < raw_count; r++) {
                const float *kv = raw_kv + (uint64_t)(raw_start + r) * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[r] = dot * scale;
                if (scores[r] > max_score) max_score = scores[r];
            }
            for (uint32_t c = 0; c < comp_count; c++) {
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                float dot = 0.0f;
                for (uint32_t d = 0; d < head_dim; d++) dot += qh[d] * kv[d];
                scores[raw_count + c] = dot * scale;
                if (scores[raw_count + c] > max_score) max_score = scores[raw_count + c];
            }
            float *oh = out_heads + ((uint64_t)t * n_head + h) * head_dim;
            memset(oh, 0, (size_t)head_dim * sizeof(float));
            float denom = expf(sinks[h] - max_score);
            for (uint32_t r = 0; r < raw_count; r++) {
                const float w = expf(scores[r] - max_score);
                denom += w;
                const float *kv = raw_kv + (uint64_t)(raw_start + r) * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t c = 0; c < comp_count; c++) {
                const float w = expf(scores[raw_count + c] - max_score);
                denom += w;
                const float *kv = comp_kv + (uint64_t)c * head_dim;
                for (uint32_t d = 0; d < head_dim; d++) oh[d] += w * kv[d];
            }
            for (uint32_t d = 0; d < head_dim; d++) oh[d] /= denom;
        }
    }
    free(scores);
}

#define SP_N_HEAD 10u
#define SP_HEAD_DIM 512u
#define SP_N_TOKENS 6u
#define SP_WINDOW 8u
#define SP_N_COMP 5u
#define SP_RATIO 2u

static int test_static_prefill_small_window(void) {
    float sinks[SP_N_HEAD];
    for (uint32_t h = 0; h < SP_N_HEAD; h++) sinks[h] = test_prand(h, 141u, 13u) * 2.0f;
    const uint64_t qn = (uint64_t)SP_N_TOKENS * SP_N_HEAD * SP_HEAD_DIM;
    const uint64_t rawn = (uint64_t)SP_N_TOKENS * SP_HEAD_DIM;
    const uint64_t compn = (uint64_t)SP_N_COMP * SP_HEAD_DIM;
    float *q = malloc((size_t)qn * sizeof(float));
    float *raw_kv = malloc((size_t)rawn * sizeof(float));
    float *comp_kv = malloc((size_t)compn * sizeof(float));
    for (uint64_t i = 0; i < qn; i++) q[i] = test_prand((uint32_t)i, 142u, 14u);
    for (uint64_t i = 0; i < rawn; i++) raw_kv[i] = test_prand((uint32_t)i, 143u, 15u);
    for (uint64_t i = 0; i < compn; i++) comp_kv[i] = test_prand((uint32_t)i, 144u, 16u);

    dh_model model = dh_model_build(sinks, SP_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc(qn * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc(rawn * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc(compn * sizeof(float));
    CHECK(theads && tq && traw && tcomp, "static prefill: alloc failed");
    CHECK(ds4_gpu_tensor_write(tq, 0, q, qn * sizeof(float)) != 0, "static prefill: q write failed");
    CHECK(ds4_gpu_tensor_write(traw, 0, raw_kv, rawn * sizeof(float)) != 0, "static prefill: raw_kv write failed");
    CHECK(ds4_gpu_tensor_write(tcomp, 0, comp_kv, compn * sizeof(float)) != 0, "static prefill: comp_kv write failed");

    CHECK(ds4_gpu_attention_prefill_static_mixed_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              SP_N_TOKENS, SP_N_COMP, SP_WINDOW, SP_RATIO, SP_N_HEAD, SP_HEAD_DIM) != 0,
          "static prefill: launch failed");

    float *got = malloc((size_t)qn * sizeof(float));
    CHECK(ds4_gpu_tensor_read(theads, 0, got, qn * sizeof(float)) != 0, "static prefill: read failed");
    float *want = malloc((size_t)qn * sizeof(float));
    oracle_attention_static_prefill(want, sinks, q, raw_kv, SP_N_TOKENS, comp_kv, SP_N_COMP,
                                    SP_WINDOW, SP_RATIO, SP_N_HEAD, SP_HEAD_DIM);
    for (uint64_t i = 0; i < qn; i++) {
        CHECK_CLOSE(got[i], want[i], 1e-3, "static prefill: heads mismatch");
    }

    free(q); free(raw_kv); free(comp_kv); free(got); free(want); free(model.bytes);
    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp);
    fprintf(stderr, "  test_static_prefill_small_window OK\n");
    return 0;
}

/* The window bound this entry enforces (window + n_comp <= 768): a call
 * exceeding it must be refused rather than silently computing anything,
 * since no cuBLAS path or scalar fallback is ported for this entry (see
 * this header's scope note). */
static int test_static_prefill_window_bound_refused(void) {
    float sinks[SP_N_HEAD] = {0};
    dh_model model = dh_model_build(sinks, SP_N_HEAD);
    ds4_gpu_tensor *theads = ds4_gpu_tensor_alloc((uint64_t)SP_N_TOKENS * SP_N_HEAD * SP_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tq = ds4_gpu_tensor_alloc((uint64_t)SP_N_TOKENS * SP_N_HEAD * SP_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *traw = ds4_gpu_tensor_alloc((uint64_t)SP_N_TOKENS * SP_HEAD_DIM * sizeof(float));
    ds4_gpu_tensor *tcomp = ds4_gpu_tensor_alloc((uint64_t)SP_N_COMP * SP_HEAD_DIM * sizeof(float));
    CHECK(theads && tq && traw && tcomp, "static prefill bound: alloc failed");

    CHECK(ds4_gpu_attention_prefill_static_mixed_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              SP_N_TOKENS, SP_N_COMP, /*window=*/800u, SP_RATIO, SP_N_HEAD, SP_HEAD_DIM) == 0,
          "static prefill bound: oversized window must be refused");
    CHECK(ds4_gpu_attention_prefill_static_mixed_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, 0u,
              /*n_tokens=*/1u, SP_N_COMP, SP_WINDOW, SP_RATIO, SP_N_HEAD, SP_HEAD_DIM) == 0,
          "static prefill bound: n_tokens == 1 must be refused (no cuBLAS/scalar fallback)");
    CHECK(ds4_gpu_attention_prefill_static_mixed_heads_tensor(
              theads, model.bytes, model.size, model.sinks_offset, tq, traw, tcomp, /*comp_kv_f16=*/1u,
              SP_N_TOKENS, SP_N_COMP, SP_WINDOW, SP_RATIO, SP_N_HEAD, SP_HEAD_DIM) == 0,
          "static prefill bound: comp_kv_f16 must be rejected");

    ds4_gpu_tensor_free(theads); ds4_gpu_tensor_free(tq); ds4_gpu_tensor_free(traw);
    ds4_gpu_tensor_free(tcomp);
    free(model.bytes);
    fprintf(stderr, "  test_static_prefill_window_bound_refused OK\n");
    return 0;
}

int main(void) {
    CHECK(ds4_gpu_init() != 0, "ds4_gpu_init failed");
    if (test_store_raw_kv() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_kv_fp8_store_raw() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_mixed_wraparound() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_raw_only() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_masked() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_heads_validation() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_raw_batch_small() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_mixed_batch_small() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_mixed_batch_online_vs_general() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_mixed_batch_online_running_max() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_decode_batch_validation() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_indexed_mixed_general() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_indexed_mixed_online(64u) != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_indexed_mixed_online(512u) != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_indexed_mixed_out_of_range_index() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_indexed_batch_validation() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_static_prefill_small_window() != 0) { ds4_gpu_cleanup(); return 1; }
    if (test_static_prefill_window_bound_refused() != 0) { ds4_gpu_cleanup(); return 1; }
    ds4_gpu_cleanup();
    fprintf(stderr, "  test_sycl_attention OK\n");
    return 0;
}
